language: ruby
rvm:
- 2.4.4
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- bundle exec rspec
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
env:
  global:
  - CC_TEST_REPORTER_ID: 85add2e883b5f810b6f6302e7e129665d580b71eb27ecad6ae7b7aa2644f1ec7
services:
- redis-server
deploy:
  provider: heroku
  app: flymyshortner
  api_key:
    secure: eeEQpOy6K7Vwrsi1DJG/m3Ix0sx24gKcNe2L0dfenRXDJ7Bv5Q2LUEnmgQSL1IjtbYxYFBmcr3ErFDb9WMbtAgZNVVHya0IL4Spm3iKU8WHwOgWEatl2R50fF7jQo4fQlRhBkkYL49FeJtXzZpJXrZKYpPP+ZIQv7EDr89Nk4u724k9xTPyqCT7f3bh43j02T3PuWj3r2BQr4SZGWCVZHgugT8Lqj5bsTDWQzYaOb03CBeaRZUacqUw8iYjPcoErZaZuwFd2nWzAO01726f0r37RPwct1QEqt8LPP7riv46UeD2zh/juJY0H2hS5C2j9tNlxAMye9hAP+ZCqRpRPzmiIZcIZRVs6V3qIkkFH/h7Qc1qj0xY6mDhk2iYYEex3fW0HY1B3nOQNFHCmkroQkgr6NTJIB+Hyw+3tb/2nzXvQg4j1BA/x1ixG0qqjXEo8Bac9divo8uBHVwdpgUofwDzCAbLSAJWEL5GNEtCsPhfk6ydVMshLqtqMgwiiCPoT7lM6xeUm3GpNI0qIBCNhm/rW/urS26BYWsbw6OryCy7wIEj5ccWGunhv75pFLRNVIhnnLS0ukOvBueVC3Ml5X7uj7565rnjq5RA3Mu2n5zjHDhkA8/A5hF877pk5EXmTmr9g57Y0xZsa/0tu69WsOrm1JLduEvEUqJdt1O4Gdhw=
  on:
    all_branches: true
