language: ruby
rvm:
- 2.4.4
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- bundle exec rspec
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
env:
  global:
  - CC_TEST_REPORTER_ID: 85add2e883b5f810b6f6302e7e129665d580b71eb27ecad6ae7b7aa2644f1ec7
services:
- redis-server
deploy:
  provider: heroku
  app: flymyshortner
  api_key:
    secure: KzoN3P2Z60PPjpiA55yN3nN17gH5OL9RxpLAwwjjNcr2EpXmtDJahwgZjMats++jj64ArUjjyeV2Y4yhQ/VaMALeo4c7GSctUbZF9+dOUqfwknF3VRM88pxueVa0aHQaGGfeOBo1s+V3AIab/3dgSvucsx6CFev2VDimN0D2y0qbS50yJAID/2iO4MHpIVVU5fVlhC77BlnCw0HaNPbjTL2NPILFTSEK8j81rxKrOf/rD/DA9HHKp3hkOdNqSd3GNYaBruAPFiwF8W3zpOtb3BycXUqOaqRa2PsraxAAM/v2Y2sWyW3es2W09gsVVh0pNmdjlmfDMaNmjpC8TK9iL/uQid6aU2enkICvcEj5MZnHaIWUgLr68p3Owaeu/t3MhYznPleXJt+VW2PTe3NV9XSdSmfnsP2iRDG7jv5d3eTnYbXPKRJCSnjBe+yl16V0UukuMGPzTjL3TOriJAeERGWK4vN/9yF0I1lcPpiShyEbNdlN6h3lYCJaY3sFGIy4jDBPEZFz76VXRQfwPttbrxzE2KpX0B5tv0OydOf1fv0Lj6T0zJ0LkWDARC4l4uraPXntumqFNHax97eQZxmH5D102ZB1imG9D9PkTaAL8ryK1qoqhADQCnHn+ErcsWPn1yT/LQf7Q9USTFgvmaGeKMBWEw4uPjUGy5VGwAS2lH8=
  on:
    all_branches: true
