language: ruby
rvm:
- 2.4.4
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- bundle exec rspec
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
env:
  global:
  - CC_TEST_REPORTER_ID: 85add2e883b5f810b6f6302e7e129665d580b71eb27ecad6ae7b7aa2644f1ec7
services:
- redis-server
deploy:
  provider: heroku
  app: flymyshortner
  api_key:
    secure: fIJXZZM3UusaauRC2xCSmHjfD23bmy/S2s0HTimu0CqyCWZbUFDm/6Ym7i/cL59KjBgpv7qgRBoQASjmFTA2/hUJhLb7H+0O6xI8+9XP6i9BDCm9oAqWtFBDxJXtq1vsL1PJJPObNzSF1xsQzzbRhZg1i1vBXAT5+O5VIh6Cu6smOviBbYGQYIAEzFHk6Hpbfj7XSnz3aA8zNifcmpF5LvNddTbG6bhwfRddzNIkO6efV5SdwvYajLb3zuSJF3S3DI54ywehhYfbv8b89eF3bCWA5DVar3+pa/OwryoSCYC9PVVDFBlbXYXM4i6UT6mGXNKaW/D4uY+kG+WsOBVjvjjk7c4P2VOEI0xIaJ57PHBVcy8eMdeDosiW/e8L6NWQ/WR0oUj+bNfBycDR1eYvc1122Ab/7xzDl0BjLOCdfqVuihJ1zMLNqwBbAzK+DoYqJe6YKF458003XRMZ19xoePi+Z0J/W39lGFULAy2tLDWnzQ97FxoIwZaxmBZNQaEa5s9EJzdh+UF3IRdVofkB/nYAwPWO+BS6r+7ABwjeDYZfWrX2uc2wdTZF1i8pxMiSiPESff3e/OgETxLcRxiVagRQVBWfD5UTNNrp81mK8XeA/oyRg2PHXXcO7YhEtxuRGndRphRVVAyvbKjzNaxGKfOKZSMXXW0EQqbUowulazg=
  on:
    all_branches: true
